// Peticiones asincronas

/*
    LAS PROMESAS TIENEN 3 ESTADOS
    PENDING -> TODAVIA NO HAY UNA RESPUESTA
    RESPONSE -> SI LA PROMESA SE CUMPLIO
    REJECTED -> RECHAZA LA PROMESA, NO SE CUMPLIO

*/